### ISSUE TITLE
Could not find a user using the email address warn_admins()

### ISSUE THREAD

**Issue by T3CHKOMMIE** [marksull/err-backend-cisco-webex-teams#21]
Hi, 

using your webexteams backend. Trying to do warm_admins() for messages that throw exceptions. 

im getting an error "Could not find a user using the email address j"

admin name in notify list is james@example.com

let me know if you need other details.

**Comment by T3CHKOMMIE** [comment]
raise FailedToFindWebexTeamsPerson(f'Could not find a user using the email address {self.email}')
yapsy_loaded_plugin_CiscoWebexTeams_0.FailedToFindWebexTeamsPerson: Could not find a user using the email address j
"
Traceback (most recent call last):
  File ".../err-backend-cisco-webex-teams/CiscoWebexTeams.py", line 127, in find_using_email
    for person in self._backend.webex_teams_api.people.list(email=self.email):
  File ".../.local/lib/python3.6/site-packages/webexteamssdk/api/people.py", line 130, in list
    for item in items:
  File ".../.local/lib/python3.6/site-packages/webexteamssdk/restsession.py", line 357, in get_items
    for json_page in pages:
  File ".../.local/lib/python3.6/site-packages/webexteamssdk/restsession.py", line 312, in get_pages
    response = self.request('GET', url, erc, params=params, **kwargs)
  File ".../.local/lib/python3.6/site-packages/webexteamssdk/restsession.py", line 250, in request
    check_response_code(response, erc)
  File ".../.local/lib/python3.6/site-packages/webexteamssdk/utils.py", line 217, in check_response_code
    raise ApiError(response)
webexteamssdk.exceptions.ApiError: [400] Bad Request - Invalid email address.

**Comment by marksull** [comment]
Check out https://github.com/marksull/err-backend-cisco-webex-teams/issues/20

**Comment by marksull** [comment]
Did ensuring your setting was a tuple sort out your issue?

**Comment by T3CHKOMMIE** [comment]
Ah damn, didn't see the comma, I'll try that tonight! Makes sense of it's a string it's only getting the first char.

**Comment by T3CHKOMMIE** [comment]
Thanks, that did it. not a tuple!
