### ISSUE TITLE
Could not find a user using the email address {self.email}

### ISSUE THREAD

**Issue by mh720** [marksull/err-backend-cisco-webex-teams#6]
Hi, i've tried bringing up errbot with your webex backend both using Docker (rroemhild/docker-errbot) and natively on a CentOS7 VM with virtualenv+python3.6. In both cases, the backend seems to be having the same issue when errbot loads it:

File "/errbot/errbackends/err-backend-cisco-webex-teams/CiscoWebexTeams.py", line 124
    raise FailedToFindWebexTeamsPerson(f'Could not find a user using the email address {self.email}')

Am I missing some BOT_X definition that this backend needs?

partial logs:
```
2018-10-11 15:45:02,414 INFO     errbot.specific_plugin_manager         CiscoWebexTeams  (/errbot/errbackends/err-backend-cisco-webex-teams/CiscoWebexTeams.py)
2018-10-11 15:45:02,415 INFO     errbot.bootstrap          Found Backend plugin: 'CiscoWebexTeams'
                                                Description: This is a backend implementation for Cisco Webex Teams
2018-10-11 15:45:02,415 DEBUG    errbot.specific_plugin_manager Refilter the plugins...
2018-10-11 15:45:02,420 DEBUG    errbot.specific_plugin_manager Load the one remaining...
2018-10-11 15:45:02,421 ERROR    yapsy                     Unable to import plugin: /errbot/errbackends/err-backend-cisco-webex-teams/CiscoWebexTeams
Traceback (most recent call last):
  File "/py36/lib/python3.4/site-packages/yapsy/PluginManager.py", line 510, in loadPlugins
    candidate_module = PluginManager._importModule(plugin_module_name, candidate_filepath)
  File "/py36/lib/python3.4/site-packages/yapsy/PluginManager.py", line 576, in _importModule
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/py36/lib64/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/py36/lib64/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/errbot/errbackends/err-backend-cisco-webex-teams/CiscoWebexTeams.py", line 124
    raise FailedToFindWebexTeamsPerson(f'Could not find a user using the email address {self.email}')
                                                                                                   ^
SyntaxError: invalid syntax
2018-10-11 15:45:02,423 ERROR    errbot.bootstrap          Unable to load or configure the backend.
```

**Comment by mh720** [comment]
Thanks Mark, that got me going. CentOS 7 is a bit behind in python, yum install python36 installed some 3.4 components. Instead, I removed it and followed the instructions at:

https://janikarhunen.fi/how-to-install-python-3-6-1-on-centos-7.html

then

pip install websockets requests ciscosparkapi

working now!

**Comment by marksull** [comment]
Glad to hear!

**Comment by mh720** [comment]
Hi Mark, stupid question, but I'm having difficulty getting the bot into a room other than from a direct conversation. What is the format for the !room join command with teams, if available?

**Comment by marksull** [comment]
I’m working on implementing the additional room commands as we speak (should be few days). In the interim add the bot to any room just as you would any other person using the Webex Teams interface.
